site_name: Materiais de Estudo - Prof. Ana Pedrosa

theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.highlight

extra_css:
  - stylesheets/style.css

nav:

  - Início:
      - Cronograma: curso/cronograma.md

  - Módulos:
      - Módulo FrontEnd: aulas/projeto_profile_digital.md

  - Material de Apoio:
      - HTML: material/html.md
      - CSS: material/css.md
      - JavaScript: material/javascript.md
      - Git: material/git.md

  - Exercícios:
      - Lista 01: exercicios/lista01.md
      - Lista 02: exercicios/lista02.md

    